Added DefCon under CyberSecurity
thisdot/tech-conferences pull request #27
Opened 2022-10-05 18:20 UTC by Sabyasachi-Seal

## Adding a conference
- [x] Suggestion is not a duplicate
- [x] Suggestion is under the proper category
- [x] Link to conference is included 
- [x] Name of conference is included
- [x] Name and link are spelled correctly

## Adding a category
- [x] Category is not a duplicate
- [x] Category is spelled properly

2022-10-05 21:50 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-05 21:50 UTC, jdwilkin4 commented on README.md
> +DEF CON is the world's premiere Hacker Conference, held annually in Las Vegas, Nevada. DEF CON is one of the oldest continuously running hacker conventions around, and also one of the largest.
```suggestion
DEF CON is the world's premiere Hacker Conference, held annually in Las Vegas, Nevada. DEF CON is one of the oldest continuously running hacker conventions around, and also one of the largest.<br>
```

2022-10-06 02:39 UTC, Sabyasachi-Seal commented
Hey @jdwilkin4 , I have made the changes as requested.
Thanks for the help :)

2022-10-06 14:55 UTC, jdwilkin4 approved these changes
Hi @Sabyasachi-Seal ! 

Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-06 14:55 UTC, merged

2022-10-06 17:11 UTC, Sabyasachi-Seal commented
Closes #24